import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    
        <div
          className="absolute inset-0 bg-cover bg-top blur-[1px] z-0"
          style={{
            backgroundImage: "url('/external/map-blue.webp')",
          }}
          />

        <div className="relative z-10 ">
          {children}
        </div>
          </>
  );
}
