import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased
          relative min-h-screen
        `}
      >
        <div
          className="absolute inset-0 bg-cover bg-top blur-[1px] z-0"
          style={{
            backgroundImage: "url('/external/map-blue.webp')",
          }}
        />

        {/* Contenido */}
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
