import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        
        

        {/* Header/Navigation */}
        <header className="w-[90vw]  mx-auto  py-4 flex justify-between items-center z-20   ">
          <div className="text-4xl font-bold text-secondary ">
            
            <p>Odisea</p>
            {/* <Image src={"/external/odisea-logo.png"} alt="odisea-logo" width={120} height={120} className="absolute top-[-2vh] " /> */}
          </div>
          <nav className="hidden md:flex items-center space-x-6">
            <Link href="/dashboard/reports" className="text-gray-600 hover:text-[#605DEC] font-semibold text-outline-white">
              Reportes
            </Link>
            <Link href="/dashboard" className="text-gray-600 hover:text-[#605DEC] font-semibold text-outline-white">
              Dashboard
            </Link>
            <Link href="/home" className="text-gray-600 hover:text-[#605DEC] font-semibold text-outline-white">
              Vuelos
            </Link>
            <Link href="#" className="text-gray-600 hover:text-[#605DEC] font-semibold">
              Ver mis vuelos
            </Link>
            <Link href="#" className="text-gray-600 hover:text-[#605DEC] font-semibold">
              Inicio de sesión
            </Link>
            <Link
              href="/auth/register"
              className="btn-secondary text-white px-4 py-2 rounded-md hover:bg-[#4F4ADB] transition-colors"
            >
              Registro
            </Link>
          </nav>
        </header>


        <div >
          {children}
        </div>
      </body>
    </html>
  );
}
